services:
  navidrome-utils:
    container_name: navidrome-utils
    image: ghcr.io/zibbp/navidrome-utils:master
    environment:
      - DEBUG=false
      - JSON=false
      - NAVIDROME_URL=http://localhost:4533
      - NAVIDROME_USERNAME=username
      - NAVIDROME_PASSWORD=password
      - NAVIDROME_DB_PATH=/data/navidrome/navidrome.db # make sure this matches the volume
      - IMPORT_PLAYLISTS_PATH=/data/playlists/input # make sure this matches the volume
    volumes:
      - ./navidrome:/data/navidrome
      - ./playlists:/data/playlists/input
